name: Copy Game Files

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Portal Site
        uses: actions/checkout@v4
        with:
          path: portal
      - name: Checkout Game Repo
        uses: actions/checkout@v4
        with:
          repository: 'mykuma0207/ny-rank-battle'
          path: game-src

      - name: Copy and Merge Files
        run: |
          mkdir -p portal/card/
          rsync -av --exclude='.git' game-src/ portal/card/
          rm -f portal/card/my-rank-battle-main.zip
